// Generated by https://quicktype.io

export interface TopLevel {
    animal:    string;
    cover_src: string;
    link:      string;
    title:     string;
}
// Generated by https://quicktype.io

export interface TopLevel {
    animal:    string;
    cover_src: string;
    link:      string;
    title:     string;
}
